server:
  port: 1039
  servlet:
    application-display-name: authorization-server
spring:
  datasource:
    url: jdbc:mysql://5.182.44.245:3306/oauthdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Vix@1400@1400@1400
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    testOnBorrow: true
    validationQuery: SELECT 1
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 2
      maximum-pool-size: 20
      pool-name: vispax_oauth_pool
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: false
logging:
  level:
    org:
      hibernate:
        type: trace

# swagger-ui custom path
springdoc:
  swagger-ui.path: /swagger-ui.html

exception.log.mode: active
